apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "headrace.fullname" . }}
  labels:
    {{- include "headrace.labels" . | nindent 4 }}
data:
  pipeline.yaml: |
    {{- toYaml .Values.pipeline | nindent 4 }}
