apiVersion: v1
kind: Service
metadata:
  name: {{ include "headrace.fullname" . }}
  labels:
    {{- include "headrace.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "headrace.selectorLabels" . | nindent 4 }}
  ports:
    - name: otlp
      port: {{ .Values.service.port }}
      targetPort: otlp
      protocol: TCP
